# Generated by Django 6.0.5 on 2026-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Experience the Art of', max_length=120)),
                ('hero_title', models.CharField(default='Luxury Fragrance', max_length=200)),
                ('hero_description', models.TextField(default='Crafted with rare ingredients to leave a timeless impression.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('hero_cta_primary_text', models.CharField(default='Explore Collection', max_length=60)),
                ('hero_cta_secondary_text', models.CharField(default='Shop Now', max_length=60)),
                ('collection_label', models.CharField(default='Our Collection', max_length=80)),
                ('collection_heading', models.CharField(default='Find Your Signature Scent', max_length=200)),
                ('excellence_label', models.CharField(default='Crafted With', max_length=80)),
                ('excellence_heading', models.CharField(default='Excellence', max_length=200)),
                ('excellence_text', models.TextField(default='Every Elvessora fragrance is composed with premium oils and refined accords — a balance of elegance, depth, and lasting presence.')),
                ('story_label', models.CharField(default='Our Story', max_length=80)),
                ('story_heading', models.CharField(default='The Art of Timeless Luxury', max_length=200)),
                ('story_text', models.TextField(blank=True)),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('story_link_text', models.CharField(default='Discover Our Journey', max_length=80)),
                ('show_favorites_picker', models.BooleanField(default=True)),
                ('show_reviews', models.BooleanField(default=True)),
                ('show_quiz_cta', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.CreateModel(
            name='HomePageHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_type', models.CharField(choices=[('hero_feature', 'Hero Feature'), ('ingredient', 'Ingredient'), ('value_prop', 'Value Proposition')], max_length=20)),
                ('icon', models.CharField(default='bi-flower1', help_text='Bootstrap Icons class, e.g. bi-flower1', max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Highlight',
                'verbose_name_plural': 'Homepage Highlights',
                'ordering': ['highlight_type', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Store Settings', 'verbose_name_plural': 'Store Settings'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='Elvessora', max_length=200),
        ),
    ]
