# Generated by Django 6.0.5 on 2026-08-05 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepage_content'),
        ('products', '0005_admin_phase2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='ISO 2-letter code', max_length=2, unique=True)),
                ('phone_code', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Override store tax for this country (optional)', max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(default='₹', max_length=8)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, help_text='Rate vs store base currency', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tracking_url_template', models.CharField(blank=True, help_text='Use {tracking} placeholder, e.g. https://track.example/{tracking}', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title',
            field=models.CharField(default='Luxury\nFragrance', max_length=200),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('object_repr', models.CharField(blank=True, max_length=250)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Login history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('flat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_days', models.CharField(blank=True, default='3-7 business days', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='shipping_zones', to='core.country')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='core.shippingprovider')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_prices', to='core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='region_prices', to='core.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_prices', to='products.product')),
            ],
            options={
                'ordering': ['country__name'],
                'unique_together': {('product', 'country')},
            },
        ),
    ]
