# Generated by Django 6.0.5 on 2026-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_admin_phase2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='AED', max_length=8),
        ),
    ]
