# Generated by Django 6.0.5 on 2026-09-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('orders_shipping', 'Orders & Shipping'), ('products_ingredients', 'Products & Ingredients'), ('payments_offers', 'Payments & Offers'), ('returns_refunds', 'Returns & Refunds'), ('fragrance_guide', 'Fragrance Guide'), ('account_support', 'Account & Support')], default='account_support', max_length=30),
        ),
    ]
