# Generated by Django 6.0.5 on 2026-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
