# Generated by Django 6.0.5 on 2026-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wishlist_guest_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='United Arab Emirates', max_length=100),
        ),
    ]
