# Generated by Django 6.0.5 on 2026-08-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Order and account updates by email.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_notifications',
            field=models.BooleanField(default=False, help_text='Order and account updates by WhatsApp.'),
        ),
    ]
