# Generated by Django 6.0.5 on 2026-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogtag_blogpost_author_image_blogpost_og_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=250),
        ),
    ]
