# Generated by Django 6.0.5 on 2026-07-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_productvariant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Inventory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.productvariant',),
        ),
    ]
