# Generated by Django 6.0.5 on 2026-08-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_admin_phase2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.IntegerField(help_text='Delta for In/Out/Correction; absolute target quantity for Set Absolute.'),
        ),
    ]
