# Generated by Django 6.0.5 on 2026-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockadjustment_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='United Arab Emirates', max_length=100),
        ),
    ]
