# Generated by Django 6.0.5 on 2026-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='buy_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Buy X (for Buy X Get Y coupons)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='get_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Get Y free (for Buy X Get Y coupons)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping'), ('bxgy', 'Buy X Get Y')], default='percent', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
