# Generated by Django 6.0.5 on 2026-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='United Arab Emirates', max_length=100),
        ),
    ]
