# Generated by Django 6.0.5 on 2026-08-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_shipping_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tamara_checkout_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tamara_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Online Payment'), ('tamara', 'Pay in Installments (Tamara)'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
