# Generated by Django 6.0.5 on 2026-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_tamara_checkout_id_order_tamara_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tabby_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Online Payment'), ('tamara', 'Pay in Installments (Tamara)'), ('tabby', 'Pay in 4 (Tabby)'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
