# Generated by Django 6.0.5 on 2026-08-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_tabby_payment_id_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amazon_fulfillment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
