# Generated by Django 6.0.5 on 2026-09-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_amazon_fulfillment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('tamara', 'Pay in Installments (Tamara)'), ('tabby', 'Pay in 4 (Tabby)'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
