# Generated by Django 5.2.17 on 2026-09-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_tap_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nomod_checkout_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('nomod', 'Pay Online (Nomod)'), ('tamara', 'Pay in Installments (Tamara)'), ('tabby', 'Pay in 4 (Tabby)'), ('tap', 'Credit / Debit Card (Tap)'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
