# Generated by Django 5.2.17 on 2026-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_nomod_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='century_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Century Express status'),
        ),
        migrations.AddField(
            model_name='order',
            name='century_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Century Express last checked'),
        ),
    ]
