# Generated by Django 6.0.5 on 2026-08-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_out_for_delivery', 'Out for Delivery'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('login_alert', 'New Login Detected')], max_length=30),
        ),
    ]
