# Generated by Django 6.0.5 on 2026-07-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['size'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory'},
        ),
    ]
