# Generated by Django 6.0.5 on 2026-08-05 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_admin_phase1_gaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.CreateModel(
            name='ProductImage360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/360/')),
                ('frame_order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_360', to='products.product')),
            ],
            options={
                'verbose_name': '360° image',
                'verbose_name_plural': '360° images',
                'ordering': ['frame_order'],
            },
        ),
    ]
